receivers:
  otlp:
    protocols:
      grpc:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:

  otlp:
    endpoint: "jaeger-all-in-one:4317"
    tls:
      insecure: true
  
  processor:
   batch:
      

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
      processors: [lobatch]