### Criar um novo leilão
POST http://localhost:8080/auction HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "product_name": "Notebook Dell",
  "category": "Eletrônicos",
  "description": "Notebook Dell i7, 16GB RAM, SSD 512GB",
  "condition": 1
}
###

### Buscar todos os leilões ativos (status=0)
GET http://localhost:8080/auction?status=0 HTTP/1.1
Host: localhost:8080

### Buscar todos os leilões completos (status=1)
GET http://localhost:8080/auction?status=1 HTTP/1.1
Host: localhost:8080
###

### Buscar leilão por ID
GET http://localhost:8080/auction/<id> HTTP/1.1
Host: localhost:8080
###

### Buscar lance vencedor de um leilão
GET http://localhost:8080/auction/winner/<id> HTTP/1.1
Host: localhost:8080
###

### Criar um novo lance 
### O usuario precisa ser criado manualmente antes de fazer um lance, utilize compass ou outro método para criar o usuário.
POST http://localhost:8080/bid HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "auction_id": "<id>",
  "user_id": "<userId>",
  "amount": 2500
}
###

### Buscar lances de um leilão
GET http://localhost:8080/bid/<userId> HTTP/1.1
Host: localhost:8080
###

### Buscar usuário por ID
GET http://localhost:8080/user/<userId> HTTP/1.1
Host: localhost:8080
###
