version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ratelimiter-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ratelimiter-network

networks:
  ratelimiter-network:
    driver: bridge
