services:
  jaeger-all-in-one:
    image: jaegertracing/jaeger:2.6.0
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
  service-a:
    container_name: serviceA
    build:
      context: .
    environment:
      - TITLE=serviceA
      - FUNCTION=inputvalidator
      - ORCHSTRATOR_URL=service-b
      - ORCHSTRATOR_PORT=28081
      - OTEL_SERVICE_NAME=serviceA
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317 # Ensure this points to the otel-collector service
      - HTTP_PORT=28080
    ports:
      - "28080:28080"
    depends_on:
      - otel-collector
      - jaeger-all-in-one
      - prometheus
  service-b:
    container_name: serviceB
    build:
      context: .
    environment:
      - TITLE=serviceB
      - FUNCTION=orchestrator
      - OTEL_SERVICE_NAME=serviceB
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317 # Ensure this points to the otel-collector service
      - HTTP_PORT=28081
      - WEATHER_API_KEY=66e971e1cd0345d595223156251405
    ports:
      - "28081:28081"
    depends_on:
      - service-a
      - otel-collector
      - jaeger-all-in-one
      - prometheus


