version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    #volumes:
      #- .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  migrations:
    image: golang:1.23-alpine3.21
    container_name: migrations
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "go run cmd/runSQLC/main.go"]
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - migrations
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}" # Web Server Port
      - "${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}" # GraphQL Server Port
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}" # GRPC Server Port
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      WEB_SERVER_PORT : ${WEB_SERVER_PORT}
      GRAPHQL_SERVER_PORT : ${GRAPHQL_SERVER_PORT}
      GRPC_SERVER_PORT : ${GRPC_SERVER_PORT}
    command: ["./main"]
