
###valid###

POST http://localhost:28080/temperature HTTP/1.1
Host: localhost:28080
Content-Type: application/json

{
  "cep": "22021001"
}
 
 
###invalid zipcode 422 ###

POST http://localhost:28080/temperature HTTP/1.1
Host: localhost:28080
Content-Type: application/json

{
  "cep": "999999998"
}

 
###Cannot find zipcode 404 ###
POST http://localhost:28080/temperature HTTP/1.1
Host: localhost:28080
Content-Type: application/json

{
  "cep": "99999999"
}
 
 

