POST http://localhost:8000/order HTTP/1.1
Host: 172.20.20.15:8000
Content-Type: application/json

{
    "id":"1",
    "price": 100.5,
    "tax": 0.5
}

###

GET http://localhost:8000/order HTTP/1.1
Host: 172.20.20.15:8000
Content-Type: application/json