
###

GET http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

//sample curl command to get all orders:
curl -X GET http://localhost:8000/order -H "Content-Type: application/json"